Fix PDF script

diff --git a/bin/pdf b/bin/pdf
--- a/bin/pdf
+++ b/bin/pdf
@@ -7,11 +7,15 @@ if [ $# -eq 0 ]
 fi
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-SLIDES=$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' $1)
+SLIDES=$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$1")
+PDF="${SLIDES}/index.pdf"
 
-cd ${DIR}
+cd "${DIR}" || (echo "Severe error" && exit)
 ./setup
 
-NAME=$(python2.7 -c "import os.path; print '-'.join(os.path.relpath('${SLIDES}','${DIR}').split(os.sep))")
+docker run --privileged -i -v "${SLIDES}":/slides/ aquilia "/pdf" > "${PDF}"
 
-docker run --privileged -it -v ${SLIDES}:/slides/ aquilia "/pdf" > "${SLIDES}/index2.pdf"
+# If PDF creation failed, it will leave a size 0 index.pdf file
+if [[ ! -s ${PDF} ]]; then
+  rm -f "${PDF}"
+fi
diff --git a/docker/pdf b/docker/pdf
--- a/docker/pdf
+++ b/docker/pdf
@@ -2,13 +2,16 @@
 
 /run &>/dev/null &
 n=0
-until [ $n -ge 5 ]
+until [ $n -ge 10 ]
 do
-   /decktape/bin/phantomjs /decktape/decktape.js http://localhost:8000 /index.pdf &> /dev/null && break
-   n=$[$n+1]
-   sleep 1
+  /decktape/bin/phantomjs /decktape/decktape.js http://localhost:8000 /index.pdf 1>&2 && break
+  n=$((n+1))
+  sleep 1
 done
-cp /index.pdf /slides/
-cat /index.pdf
+if [[ -f /index.pdf ]]; then
+  cat /index.pdf
+else
+  echo "Failed to create PDF" 1>&2
+fi
 kill %1 &>/dev/null
 exit
